#!/usr/bin/env python3
"""
init_agent.py - Scaffold and manage a project-aware LLM agent.

Subcommands:
  init        Create .ai/knowledgebase/, .ai/agent/phases/ and CLAUDE.md
  new-ticket  Scaffold tasks/<ticket-id>/ (ticket.md, plan.md)
  archive     Move a finished ticket to tasks/_archive/ (all tasks must be done)

Context layout:
  CLAUDE.md                    always loaded: KB protocol, budgets, generated
                               project-context section, phase pointer table
  .ai/agent/phases/*.md        loaded on demand, only when the phase runs

Versioning:
  .ai/ is excluded from the host project's repo (init appends it to the
  project .gitignore) and tracked in its own git repo at .ai/.git. Every
  subcommand commits its changes there. CLAUDE.md stays in the host repo.

Generated docs use two language registers (concept v4, CONCEPT.md section 8):
normative docs (CLAUDE.md protocol, phase docs) in plain imperative English,
KB content (node summaries, tickets) telegraphic. Identifiers verbatim.

Usage:
  python init_agent.py init [project_dir] [--force] [--project-name NAME]
  python init_agent.py new-ticket TICKET_ID [project_dir] [--title TITLE]
  python init_agent.py archive TICKET_ID [project_dir] [--force]
"""

import argparse
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

TODAY = date.today().isoformat()

# ---------------------------------------------------------------- structure

KB_DIRS = [
    "architecture",
    "conventions",
    "domain",
    "infra",
    "decisions",
    "tasks",
    "tasks/_archive",
]

HOT_NODES = {
    "architecture/overview.md": {
        "id": "architecture/overview",
        "summary": "High-level architecture: modules, data flow, entry points",
        "tags": ["architecture", "overview"],
        "covers": ["src/**"],
        "tier": "hot",
        "body": (
            "# Architecture Overview\n\n"
            "<!-- Filled in Phase 1 (Initialization). -->\n\n"
            "## Modules\n\n## Data Flow\n\n## Entry Points\n"
        ),
    },
    "conventions/code-style.md": {
        "id": "conventions/code-style",
        "summary": "Code style, naming, formatting, linting rules",
        "tags": ["conventions", "style", "lint"],
        "covers": ["**/*"],
        "tier": "hot",
        "body": (
            "# Code Style\n\n"
            "<!-- Source: linter configs + user Q&A at init. -->\n"
        ),
    },
    "domain/glossary.md": {
        "id": "domain/glossary",
        "summary": "Domain terms and their precise project meaning",
        "tags": ["domain", "glossary"],
        "covers": [],
        "tier": "hot",
        "body": "# Glossary\n\n| Term | Meaning |\n|---|---|\n",
    },
}

COLD_NODE_TEMPLATES = {
    "conventions/testing.md": {
        "id": "conventions/testing",
        "summary": "Test layout, frameworks, coverage expectations",
        "tags": ["conventions", "testing"],
        "covers": ["tests/**", "**/*test*"],
        "tier": "cold",
        "body": "# Testing Conventions\n\n<!-- Filled at init. -->\n",
    },
    "conventions/git-workflow.md": {
        "id": "conventions/git-workflow",
        "summary": "Branching, commit message rules, review gates",
        "tags": ["conventions", "git"],
        "covers": [],
        "tier": "cold",
        "body": "# Git Workflow\n\n<!-- Filled at init. -->\n",
    },
    "infra/build.md": {
        "id": "infra/build",
        "summary": "Build system, targets, local dev setup",
        "tags": ["infra", "build"],
        "covers": ["Makefile", "*.toml", "*.gradle", "CMakeLists.txt", "package.json"],
        "tier": "cold",
        "body": "# Build\n\n<!-- Filled at init. -->\n",
    },
    "infra/ci-cd.md": {
        "id": "infra/ci-cd",
        "summary": "CI/CD pipelines, stages, deployment targets",
        "tags": ["infra", "ci", "cd"],
        "covers": [".github/**", ".gitlab-ci.yml", "Jenkinsfile"],
        "tier": "cold",
        "body": "# CI/CD\n\n<!-- Filled at init. -->\n",
    },
}

ALL_NODES = {**HOT_NODES, **COLD_NODE_TEMPLATES}

PHASES_DIR = ".ai/agent/phases"


# --------------------------------------------------------------- rendering

def frontmatter(meta: dict) -> str:
    tags = ", ".join(meta["tags"])
    covers = ", ".join(f'"{c}"' for c in meta["covers"])
    return (
        "---\n"
        f"id: {meta['id']}\n"
        f"summary: {meta['summary']}\n"
        f"tags: [{tags}]\n"
        f"covers: [{covers}]\n"
        f"tier: {meta['tier']}\n"
        f"updated: {TODAY}\n"
        "related: []\n"
        "---\n\n"
    )


def render_manifest(project_name: str) -> str:
    lines = [
        f"# Generated by init_agent.py on {TODAY}. Machine-readable KB index.",
        f"project: {project_name}",
        "budgets:",
        "  claude_md_max_tokens: 2000",
        "  generated_section_max_tokens: 1500",
        "  per_task_max_nodes: 4",
        "  per_task_max_tokens: 6000",
        "  related_hops: 1",
        "  budget_policy: soft  # overrun allowed; state reason in one line, log it",
        "nodes:",
    ]
    for path, meta in sorted(ALL_NODES.items()):
        covers = ", ".join(f'"{c}"' for c in meta["covers"])
        tags = ", ".join(meta["tags"])
        lines += [
            f"  - id: {meta['id']}",
            f"    path: {path}",
            f"    summary: {meta['summary']}",
            f"    tags: [{tags}]",
            f"    covers: [{covers}]",
            f"    tier: {meta['tier']}",
            f"    updated: {TODAY}",
        ]
    return "\n".join(lines) + "\n"


def render_index(project_name: str) -> str:
    lines = [
        f"# Knowledge Base Index: {project_name}",
        "",
        "<!-- GENERATED from manifest.yaml. Do not edit. -->",
        "",
        "| Node | Tier | Load when |",
        "|---|---|---|",
    ]
    for path, meta in sorted(ALL_NODES.items()):
        lines.append(f"| `{path}` | {meta['tier']} | {meta['summary']} |")
    return "\n".join(lines) + "\n"


def render_claude_md(project_name: str) -> str:
    return f"""# Agent: {project_name}

Project-aware agent (concept v4). KB = `.ai/knowledgebase/`. Token efficiency
is a hard requirement; this file stays under 2000 tokens. Phase instructions
live in `{PHASES_DIR}/` and are loaded only when the phase runs. Write
normative instructions in plain imperative English; write KB content
telegraphic. Keep identifiers, paths, and commands verbatim.

## Phases

| Phase | Read first (mandatory, before any other step) |
|---|---|
| 1 Initialization | `{PHASES_DIR}/init.md` |
| 2 Planning | `{PHASES_DIR}/planning.md` |
| 3 Implementation | `{PHASES_DIR}/implementation.md` |
| 4 Operational | none. Protocol below = default behavior |

## KB Protocol

1. Parse `.ai/knowledgebase/manifest.yaml` first. Never load all nodes.
2. Hot-tier content is embedded in the Project Context section below. Never
   load `tier: hot` nodes separately.
3. Match the task against `covers` globs and `tags` first (stage 1, exact).
   Only on a miss, keyword-score the manifest summaries (stage 2).
4. Budgets are soft targets: aim for at most 4 cold nodes / 6000 tokens per
   task, and follow `related` links at most 1 hop. If you must exceed a
   budget, state the reason in one line, proceed, and log the overrun.
   Recall beats precision: never skip context you need just to stay under
   budget.
5. Cache loaded node ids per session. Invalidate the cache after context
   compaction; summarized content no longer counts as loaded.
6. Mark loaded nodes as used or unused (compaction telemetry).
7. Never load `tasks/_archive/`.
8. Session hygiene: clear bulky tool results after extracting what you need.
   Run exploration in sub-agent contexts when the harness supports them.
9. Invariants: single source of truth, never duplicate. Split a node over
   ~1500 tokens and cross-link the parts.

## Ticket Layout

```
tasks/<ticket-id>/
  ticket.md       # original ticket + recorded Q&A answers
  plan.md         # task index; frontmatter carries read-first pointer
  NN-<slug>.md    # one file per task, self-contained
  kb-delta.yaml   # accumulated KB patches
tasks/_archive/   # finished tickets; never load
```

Status in frontmatter (`planned|in-progress|done|blocked`), never in folder
names. Archive finished tickets: `python init_agent.py archive <id>`.

## Model Routing (default)

Planning + tasks `complexity: high` → high-reasoning model. `low`/`med` →
cost-efficient model. Escalation rules in `{PHASES_DIR}/implementation.md`
override.

## Project Context

<!-- BEGIN GENERATED:project-context (source: hot-tier nodes, max 1500 tokens) -->
<!-- Populated in Phase 1. Do not edit. -->
<!-- END GENERATED:project-context -->
"""


def render_phase_init() -> str:
    return f"""# Phase 1: Initialization

Read this before analyzing the project.

## Strategy
- Sample, do not scan everything: per module, read entry points, public API,
  and tests.
- Run exploration in isolated sub-agent contexts when the harness supports
  them. Each sub-agent returns a condensed summary of at most 2000 tokens.
  Keep raw file dumps out of the synthesizing context.
- Build KB nodes bottom-up: module nodes first, then the architecture
  overview.
- After node changes, regenerate `manifest.yaml` and `INDEX.md`.
- Regenerate the `GENERATED:project-context` section in CLAUDE.md from the
  hot-tier nodes, condensed: project one-liner, tech stack, build/test/lint
  commands, top conventions, module map (one line per module plus cold-node
  ref), core glossary terms. Cap: 1500 tokens.

## Non-derivable knowledge
Ask the user about domain terms, unwritten conventions, and ownership.
Record the answers directly in the matching KB nodes.

## Incrementality
Record the commit SHA and per-file hashes. A re-init processes only the diff.

## Output
Produce a coverage report: areas read vs skipped (lazy-init candidates for
Phase 4).
"""


def render_phase_planning() -> str:
    return f"""# Phase 2: Planning (high-reasoning model)

Read this before decomposing a ticket.

## Workflow
1. Scaffold: `python init_agent.py new-ticket <ticket-id>`.
2. Load matched KB nodes (protocol budgets apply).
3. Run interactive Q&A with the user until the acceptance criteria are
   unambiguous. Keep the rounds bounded. Record answers in `ticket.md`.
4. Write one task file per task. `plan.md` stays a thin index.
5. Plan-review gate: review the finished plan against the acceptance
   criteria yourself, then get user sign-off on `plan.md` before
   implementation starts. A weak plan poisons every downstream task.

## Task file format (`NN-<slug>.md`)
Frontmatter: `status: planned`, `complexity: low|med|high`, `depends: []`.
Body, self-contained:
- Goal and testable acceptance criteria
- Affected files with explicit paths
- Pre-bound KB node ids with content hashes
- Expected signatures/interfaces
- Test skeletons

Pre-binding is a warm start, not a contract: implementation starts from the
bound nodes and files and may run at most 5 targeted searches of its own
before escalating `missing-context`.

## plan.md
Index only: order, dependencies, complexity, routing, status. The
frontmatter `read-first` pointer forces the implementation model to load its
phase doc. Do not remove it.

## Routing
Set `complexity` per task. `high` routes to the high-reasoning model, even
during the implementation phase.
"""


def render_phase_implementation() -> str:
    return """# Phase 3: Implementation (cost-efficient model)

Read this before executing any task.

## Load discipline
Load only: `plan.md`, the single current task file, its pre-bound KB nodes,
and the listed files. You may run at most 5 targeted searches beyond that.
Never load the whole ticket folder.

## Hash check (diff-aware)
Verify the pre-bound node content hashes before starting. On drift, diff the
current node content against the bound hash:
- If the delta does not touch the task's interfaces or acceptance criteria,
  proceed on the fresh content.
- If it does, stop and re-plan the affected task only (escalate to the
  planning model).
Never proceed silently on stale context. Never trigger a full re-plan for
cosmetic drift.

## Definition of done (per task)
- Tests pass and lint is clean
- Task frontmatter is `status: done`
- A KB patch is appended to `kb-delta.yaml`:
  `op: update|create|split`, `node: <id>`, `diff: <content>`

## Escalation (typed; never improvise around a blocker)
- `missing-context`: use your bounded discovery first, then reload KB (1 hop,
  in a sub-agent when available), then upgrade the model.
- `ambiguity`: ask the user.
- `test-fail` twice: upgrade the model, for this task only.

## KB maintenance
- `kb-delta.yaml` auto-apply covers metadata and `covers` changes only.
  Structural changes go through the review gate.
- After hot-tier node updates, regenerate `GENERATED:project-context` in
  CLAUDE.md.
- ADRs (`decisions/`) are append-only. Supersede via link, never edit.
- Narrow the triggers of nodes that are loaded but unused in more than 50%
  of tasks.
"""


def render_ticket_md(ticket_id: str, title: str) -> str:
    return (
        "---\n"
        f"id: {ticket_id}\n"
        f"title: {title}\n"
        "status: planned\n"
        f"created: {TODAY}\n"
        "---\n\n"
        f"# {ticket_id}: {title}\n\n"
        "## Description\n\n<!-- Original ticket here. -->\n\n"
        "## Q&A (Planning)\n\n<!-- Recorded clarification answers. -->\n"
    )


def render_plan_md(ticket_id: str) -> str:
    return (
        "---\n"
        f"ticket: {ticket_id}\n"
        "status: planned\n"
        f"read-first: {PHASES_DIR}/implementation.md\n"
        f"updated: {TODAY}\n"
        "---\n\n"
        f"# Plan: {ticket_id}\n\n"
        "<!-- Implementation model: read read-first file above before any task. -->\n\n"
        "| # | Task file | Depends on | Complexity | Model | Status |\n"
        "|---|---|---|---|---|---|\n"
        "<!-- One row per NN-<slug>.md task file. -->\n"
    )


# ------------------------------------------------------------------ helpers

def write(path: Path, content: str, force: bool, created: list, skipped: list):
    if path.exists() and not force:
        skipped.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    created.append(path)


def report(root: Path, created: list, skipped: list):
    for p in created:
        print(f"created  {p.relative_to(root)}")
    for p in skipped:
        print(f"skipped  {p.relative_to(root)} (exists, use --force)")


def read_status(path: Path) -> str:
    m = re.search(r"^status:\s*(\S+)", path.read_text(encoding="utf-8"), re.M)
    return m.group(1) if m else "unknown"


def project_root(project_dir: str) -> Path:
    root = Path(project_dir).resolve()
    if not root.is_dir():
        sys.exit(f"error: {root} is not a directory")
    return root


# ----------------------------------------------------------------------- git

def run_git(args: list, cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)


def ensure_gitignore(root: Path):
    """Exclude .ai/ from the host project's repo (only if root is a git repo)."""
    if not (root / ".git").exists():
        return
    gitignore = root / ".gitignore"
    lines = gitignore.read_text(encoding="utf-8").splitlines() if gitignore.exists() else []
    if any(line.strip().lstrip("/").rstrip("/") == ".ai" for line in lines):
        return
    content = "\n".join(lines).rstrip("\n")
    content = (content + "\n" if content else "") + ".ai/\n"
    gitignore.write_text(content, encoding="utf-8")
    print(f"updated  {gitignore.relative_to(root)} (+ .ai/)")


def ai_commit(root: Path, message: str):
    """Track .ai/ in its own repo; commit pending changes with message."""
    ai_dir = root / ".ai"
    if not ai_dir.is_dir():
        return
    if shutil.which("git") is None:
        print("warning: git not found; .ai changes not committed")
        return
    if not (ai_dir / ".git").exists():
        r = run_git(["init"], ai_dir)
        if r.returncode != 0:
            print(f"warning: git init failed in .ai: {r.stderr.strip()}")
            return
        print("initialized git repo in .ai/")
    run_git(["add", "-A"], ai_dir)
    if run_git(["diff", "--cached", "--quiet"], ai_dir).returncode == 0:
        return  # nothing staged
    r = run_git(["commit", "-m", message], ai_dir)
    if r.returncode != 0:
        print(f"warning: commit in .ai failed: {r.stderr.strip() or r.stdout.strip()}")
    else:
        print(f"committed in .ai: {message}")


# -------------------------------------------------------------- subcommands

def cmd_init(args) -> int:
    root = project_root(args.project_dir)
    name = args.project_name or root.name
    kb = root / ".ai" / "knowledgebase"
    created, skipped = [], []

    for d in KB_DIRS:
        (kb / d).mkdir(parents=True, exist_ok=True)
        if not any((kb / d).iterdir()):
            (kb / d / ".gitkeep").touch()

    for rel, meta in ALL_NODES.items():
        write(kb / rel, frontmatter(meta) + meta["body"], args.force, created, skipped)

    write(kb / "manifest.yaml", render_manifest(name), args.force, created, skipped)
    write(kb / "INDEX.md", render_index(name), args.force, created, skipped)

    phases = root / PHASES_DIR
    write(phases / "init.md", render_phase_init(), args.force, created, skipped)
    write(phases / "planning.md", render_phase_planning(), args.force, created, skipped)
    write(phases / "implementation.md", render_phase_implementation(),
          args.force, created, skipped)

    write(root / "CLAUDE.md", render_claude_md(name), args.force, created, skipped)

    ensure_gitignore(root)
    ai_commit(root, f"init: scaffold KB + phase docs ({name})")

    report(root, created, skipped)
    print(f"\nKB: {kb.relative_to(root)}  |  phases: {PHASES_DIR}"
          f"  |  nodes: {len(ALL_NODES)}  |  project: {name}")
    return 0


def cmd_new_ticket(args) -> int:
    root = project_root(args.project_dir)
    tdir = root / ".ai" / "knowledgebase" / "tasks" / args.ticket_id
    if tdir.exists():
        sys.exit(f"error: ticket {args.ticket_id} already exists at {tdir}")
    title = args.title or args.ticket_id
    created, skipped = [], []
    write(tdir / "ticket.md", render_ticket_md(args.ticket_id, title), False, created, skipped)
    write(tdir / "plan.md", render_plan_md(args.ticket_id), False, created, skipped)
    report(root, created, skipped)
    ai_commit(root, f"new-ticket: {args.ticket_id}")
    return 0


def cmd_archive(args) -> int:
    root = project_root(args.project_dir)
    tasks_dir = root / ".ai" / "knowledgebase" / "tasks"
    tdir = tasks_dir / args.ticket_id
    if not tdir.is_dir():
        sys.exit(f"error: ticket {args.ticket_id} not found at {tdir}")

    open_items = []
    plan = tdir / "plan.md"
    if plan.exists() and read_status(plan) != "done":
        open_items.append((plan, read_status(plan)))
    for task_file in sorted(tdir.glob("[0-9][0-9]-*.md")):
        st = read_status(task_file)
        if st != "done":
            open_items.append((task_file, st))

    if open_items and not args.force:
        print(f"error: ticket {args.ticket_id} has unfinished items:", file=sys.stderr)
        for p, st in open_items:
            print(f"  {p.relative_to(root)}  status={st}", file=sys.stderr)
        print("use --force to archive anyway", file=sys.stderr)
        return 1

    if not (tdir / "kb-delta.yaml").exists():
        print("warning: no kb-delta.yaml found; verify KB updates were applied")

    dest = tasks_dir / "_archive" / args.ticket_id
    if dest.exists():
        sys.exit(f"error: {dest} already exists in archive")
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(tdir), str(dest))
    print(f"archived  {tdir.relative_to(root)} -> {dest.relative_to(root)}")
    ai_commit(root, f"archive: ticket {args.ticket_id}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("init", help="scaffold KB, phase docs and CLAUDE.md")
    p.add_argument("project_dir", nargs="?", default=".")
    p.add_argument("--force", action="store_true")
    p.add_argument("--project-name", default=None)
    p.set_defaults(func=cmd_init)

    p = sub.add_parser("new-ticket", help="scaffold a ticket folder")
    p.add_argument("ticket_id")
    p.add_argument("project_dir", nargs="?", default=".")
    p.add_argument("--title", default=None)
    p.set_defaults(func=cmd_new_ticket)

    p = sub.add_parser("archive", help="archive a finished ticket")
    p.add_argument("ticket_id")
    p.add_argument("project_dir", nargs="?", default=".")
    p.add_argument("--force", action="store_true",
                   help="archive even with unfinished tasks")
    p.set_defaults(func=cmd_archive)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
