"""Every render_* entry point.

These are thin now: each one computes whatever varies on profile or harness
and hands the rest to a template under `templates/`. The prose itself is not
here, which is the point. Adding a skill means adding a template file and a
name to the roster in `const`, not editing a string in Python.
"""

import json

from agentgen import render
from agentgen.const import *  # noqa: F403  shared paths, markers, rosters
# `import *` skips underscore names; these are internal but shared.
from agentgen.const import _MANIFEST_PARSER, _SKILL_DESCRIPTIONS

def seed_description(description: str):
    """Seed the user-supplied one-liner into the overview node.

    HOT_NODES and ALL_NODES share meta dicts, so mutating in place updates
    the node file, manifest.yaml and INDEX.md in one go.
    """
    meta = HOT_NODES["architecture/overview.md"]
    meta["summary"] = description
    meta["body"] = (
        "# Architecture Overview\n\n"
        f"{description}\n\n"
        "<!-- Description seeded at init: verify against the code in Phase 1. -->\n\n"
        "## Modules\n\n## Data Flow\n\n## Entry Points\n"
    )

def frontmatter(meta: dict) -> str:
    tags = ", ".join(meta["tags"])
    covers = ", ".join(f'"{c}"' for c in meta["covers"])
    return (
        "---\n"
        f"id: {meta['id']}\n"
        f"summary: {meta['summary']}\n"
        f"tags: [{tags}]\n"
        f"covers: [{covers}]\n"
        f"tier: {meta['tier']}\n"
        f"updated: {TODAY}\n"
        "related: []\n"
        "---\n\n"
    )

def render_manifest(project_name: str, description: str = "") -> str:
    lines = [
        f"# Generated by init_agent.py on {TODAY}. Machine-readable KB index.",
        f"project: {project_name}",
    ]
    if description:
        lines.append(f"description: {description}")
    lines += [
        "budgets:",
        "  agents_md_max_tokens: 2000",
        "  generated_section_max_tokens: 1500",
        "  per_task_max_nodes: 4",
        "  per_task_max_tokens: 6000",
        "  related_hops: 1",
        "  budget_policy: soft  # overrun allowed; state reason in one line",
        "nodes:",
    ]
    for path, meta in sorted(ALL_NODES.items()):
        covers = ", ".join(f'"{c}"' for c in meta["covers"])
        tags = ", ".join(meta["tags"])
        lines += [
            f"  - id: {meta['id']}",
            f"    path: {path}",
            f"    summary: {meta['summary']}",
            f"    tags: [{tags}]",
            f"    covers: [{covers}]",
            f"    tier: {meta['tier']}",
            f"    updated: {TODAY}",
        ]
    return "\n".join(lines) + "\n"

def render_index(project_name: str) -> str:
    lines = [
        f"# Knowledge Base Index: {project_name}",
        "",
        "<!-- GENERATED from manifest.yaml by gen_index.py. Do not edit. -->",
        "",
        "| Node | Tier | Load when |",
        "|---|---|---|",
    ]
    for path, meta in sorted(ALL_NODES.items()):
        lines.append(f"| `{path}` | {meta['tier']} | {meta['summary']} |")
    return "\n".join(lines) + "\n"

def render_agents_md(project_name: str, description: str = "",
                     harness: str = "claude",
                     generated_body: str = None) -> str:
    if generated_body is None:
        seed = f"{description}\n" if description else ""
        generated_body = f"{seed}<!-- Populated in Phase 1. Do not edit. -->"
    cli_note = ""
    if harness == "copilot":
        cli_note = render.fill("instructions/fragments/copilot/cli-note-large.md",
                              phases_dir=PHASES_DIR)
    hook_note = (render.load("instructions/fragments/claude/hook-note.md")
                 if harness == 'claude' else '')
    rules_note = (render.fill("instructions/fragments/claude/rules-note.md",
                              tools_dir=TOOLS_DIR)
                 if harness == 'claude' else '')
    entry_note = ("packaged as Agent Skills under `.claude/skills/`"
                  if harness == "claude"
                  else "exposed as prompt files under `.github/prompts/`")
    goal_note = ""
    if harness == "claude":
        goal_note = render.load("instructions/fragments/claude/goal-note-large.md")
    return render.fill("instructions/agents-large.md",
                       cli_note=cli_note,
                       entry_note=entry_note,
                       gen_begin=GEN_BEGIN,
                       gen_end=GEN_END,
                       generated_body=generated_body,
                       goal_note=goal_note,
                       hook_note=hook_note,
                       phases_dir=PHASES_DIR,
                       project_name=project_name,
                       rules_note=rules_note,
                       tools_dir=TOOLS_DIR)

def render_claude_pointer() -> str:
    return (
        "# CLAUDE.md\n\n"
        "Canonical agent instructions live in AGENTS.md (vendor-neutral).\n"
        "Imported below; do not duplicate content here.\n\n"
        "@AGENTS.md\n"
    )

def render_agents_md_small(project_name: str, description: str = "",
                           harness: str = "claude",
                           generated_body: str = None) -> str:
    """Small-profile AGENTS.md: dense, self-contained. No KB protocol, no
    budgets table, no phase pointers. The generated project-context section is
    the only knowledge store; the source code is read on demand."""
    if generated_body is None:
        seed = f"{description}\n" if description else ""
        generated_body = (f"{seed}<!-- Populated by /explore. "
                          "Do not edit by hand. -->")
    hook_note = (render.load("instructions/fragments/claude/hook-note-small.md")
                 if harness == 'claude' else '')
    entry_note = ("packaged as Agent Skills under `.claude/skills/`"
                  if harness == "claude"
                  else "exposed as prompt files under `.github/prompts/`")
    cli_note = ""
    if harness == "copilot":
        cli_note = render.load("instructions/fragments/copilot/cli-note-small.md")
    goal_note = ""
    if harness == "claude":
        goal_note = render.load("instructions/fragments/claude/goal-note-small.md")
    return render.fill("instructions/agents-small.md",
                       cli_note=cli_note,
                       entry_note=entry_note,
                       gen_begin_small=GEN_BEGIN_SMALL,
                       gen_end=GEN_END,
                       generated_body=generated_body,
                       goal_note=goal_note,
                       hook_note=hook_note,
                       project_name=project_name)

def render_notes_stub() -> str:
    return render.fill("config/notes-stub.md")

def render_phase_init(harness: str = "claude") -> str:
    perms = (
        " Shell\n"
        "  commands you do need are pre-allowed in `.claude/settings.json`\n"
        "  (read-only list)." if harness == "claude" else ""
    )
    hook_offer = ""
    if harness == "claude":
        hook_offer = render.load("phases/fragments/claude/hook-offer.md")
    rules_line = ""
    if harness == "claude":
        rules_line = render.load("phases/fragments/claude/rules-line.md")
    return render.fill("phases/init.md",
                       hook_offer=hook_offer,
                       perms=perms,
                       rules_line=rules_line,
                       tools_dir=TOOLS_DIR)

def render_phase_planning() -> str:
    return render.fill("phases/planning.md",
                       phases_dir=PHASES_DIR)

def render_phase_implementation(harness: str = "claude") -> str:
    rules_bullet = ""
    if harness == "claude":
        rules_bullet = render.fill("phases/fragments/claude/rules-bullet.md",
                              tools_dir=TOOLS_DIR)
    return render.fill("phases/implementation.md",
                       rules_bullet=rules_bullet,
                       tools_dir=TOOLS_DIR)

def render_update_body(size: str, harness: str, arg: str) -> str:
    """Body of the /update skill: an agent-driven framework update.

    A scaffolder can only own files whole (regenerate or freeze), which is why
    updating used to lose user edits, keep retired files, and never migrate the
    shape of hand-filled content. Those are merge decisions, so the agent makes
    them. The rule the whole procedure serves: the knowledge base is the
    expensive artifact, so an update migrates it and never re-derives it.

    Varies on both axes: the large profile has a KB, manifest, INDEX and
    generated tools to migrate; the small profile has notes and specs. Harness
    decides which framework files exist to merge (settings/hooks/skills on
    claude, prompt files on copilot).
    """
    if harness == "claude":
        backup_paths = "AGENTS.md, CLAUDE.md, and `.claude/`"
        merge_cases = (
            "     - `.claude/settings.json`: permission entries and hooks a user\n"
            "       added are not framework state. Union them with the\n"
            "       reference's; drop only entries the reference retired.\n"
            "     - AGENTS.md outside the GENERATED markers: project-specific\n"
            "       rules a user appended below the framework text.\n"
            "     - skills, hooks, or sub-agents present here but not in the\n"
            "       reference: the user's own, unless the generator's history\n"
            "       says otherwise. Settle it with the orphan test below rather\n"
            "       than assuming either way.\n")
        verify_extra = (
            "   - `.claude/settings.json` parses as JSON and every hook command\n"
            "     it names points at a file that exists.\n")
    else:
        backup_paths = "AGENTS.md and `.github/prompts/`"
        merge_cases = (
            "     - AGENTS.md outside the GENERATED markers: project-specific\n"
            "       rules a user appended below the framework text.\n"
            "     - prompt files under `.github/prompts/` present here but not in\n"
            "       the reference: the user's own, unless the generator's history\n"
            "       says otherwise. Settle it with the orphan test below rather\n"
            "       than assuming either way.\n")
        verify_extra = ""

    if size == "large":
        owned = ("KB nodes under `.ai/knowledgebase/`, `manifest.yaml`,\n"
                 "`INDEX.md`, `.ai/notes.md`, tickets, task files, and the\n"
                 "`GENERATED:project-context` section of AGENTS.md")
        migrate = (
            "   - New or renamed frontmatter keys on KB nodes: add them, deriving\n"
            "     values from the node's own content and `covers` globs.\n"
            "   - New fields or sections in `manifest.yaml`: fill them from the\n"
            "     KB, never from the reference's stub values.\n"
            "   - Moved or renamed directories: `git mv` inside `.ai` so the KB\n"
            "     history survives the move.\n")
        regen = (
            f"   Then rebuild only what is derived: `python3 {TOOLS_DIR}/gen_index.py`\n"
            "   regenerates `INDEX.md` from `manifest.yaml`, so it is always safe.\n")
        verify_tools = (f"`{TOOLS_DIR}/probe.py`, `{TOOLS_DIR}/gen_index.py`,\n"
                        f"     and `{TOOLS_DIR}/check_stale.py`")
    else:
        owned = ("`.ai/notes.md`, `.ai/notes/<topic>.md`, change specs under\n"
                 "`.ai/changes/`, and the `GENERATED:project-context` section of\n"
                 "AGENTS.md")
        migrate = (
            "   - New or renamed sections in the project-context digest: add the\n"
            "     heading and move the matching content that is already there\n"
            "     under it. Do not re-derive the content from the codebase.\n"
            "   - A changed spec format: bring existing `.ai/changes/<id>/spec.md`\n"
            "     files up to it, keeping every goal, criterion, and task intact.\n"
            "   - Moved or renamed directories: `git mv` inside `.ai` so the notes\n"
            "     history survives the move.\n")
        regen = ""
        verify_tools = f"`{TOOLS_DIR}/probe.py`"

    return render.fill("skills/bodies/update.md",
                       arg=arg,
                       backup_paths=backup_paths,
                       framework_json=FRAMEWORK_JSON,
                       harness=harness,
                       merge_cases=merge_cases,
                       migrate=migrate,
                       owned=owned,
                       regen=regen,
                       size=size,
                       verify_extra=verify_extra,
                       verify_tools=verify_tools)

def render_tidy_up_body(size: str, harness: str, arg: str) -> str:
    """Body of the /tidy-up skill: a bounded hygiene sweep over the host code.

    Four passes with deliberately different authority. Removing dead code and
    rewriting comments or prose is reversible and locally verifiable, so the
    agent does it. Deleting a file is neither, so that pass only proposes. The
    rule the whole procedure serves: a tidy-up may not change behavior, so
    every pass is gated on the same test and lint baseline captured up front.

    Varies on both axes: the large profile has KB nodes whose `covers` globs
    can point at removed paths; the small profile has notes plus the
    project-context digest. Harness decides whether the survey fan-out and the
    review gate can run in sub-agents.
    """
    if harness == "claude":
        survey_note = (
            "   Dispatch the survey fan-out to sub-agents where the harness\n"
            "   supports them: each returns a candidate list with evidence, not\n"
            "   file dumps. Decide every removal yourself.\n")
        review_note = (
            "   Run the `reviewer` sub-agent on the full diff. If it cannot be\n"
            "   spawned, use a fresh general-purpose sub-agent given only the\n"
            "   diff and the rule that behavior must not change.\n")
    else:
        survey_note = (
            "   Survey with your read and search tools; keep raw file dumps out\n"
            "   of context by searching for evidence, not by reading whole trees.\n")
        review_note = (
            "   Re-read the full diff in a clean context against the rule that\n"
            "   behavior must not change, and note that no reviewer sub-agent\n"
            "   was available.\n")

    if size == "large":
        record = (
            "   Removing code can invalidate the KB. For every node whose\n"
            "   `covers` globs matched a removed path, update the node and its\n"
            f"   `manifest.yaml` entry, then run `python3 {TOOLS_DIR}/gen_index.py`.\n"
            "   Update the `GENERATED:project-context` module map only if a\n"
            "   module disappeared or was renamed.\n")
    else:
        record = (
            "   If a module disappeared or was renamed, update the module map in\n"
            "   the `GENERATED:project-context` section of AGENTS.md. Append any\n"
            "   durable finding to `.ai/notes.md`, for example a subsystem that\n"
            "   turned out to be unreachable.\n")

    return render.fill("skills/bodies/tidy-up.md",
                       arg=arg,
                       record=record,
                       review_note=review_note,
                       survey_note=survey_note)

def command_specs(harness: str, arg_focus: str, arg_ticket: str) -> list:
    """(name, description, body) for each large-profile command.

    Bodies live under templates/skills/large/; this function decides which
    skills the profile carries, in what order, and what each body's slots are
    filled with. Two bodies are composed rather than loaded because they vary
    on profile and harness beyond simple slot filling.
    """
    return _load_specs(
        "large", SKILLS_LARGE, harness, arg_focus, arg_ticket,
        hook_offer="")

def command_specs_small(harness: str, arg_focus: str, arg_ticket: str) -> list:
    """(name, description, body) for each small-profile command.

    Self-contained bodies (no phase-doc layer), under templates/skills/small/.
    """
    hook_offer = (render.load("skills/fragments/claude/hook-offer.md")
                  if harness == "claude" else "")
    return _load_specs(
        "small", SKILLS_SMALL, harness, arg_focus, arg_ticket,
        hook_offer=hook_offer)

COMPOSED_BODIES = {
    "tidy-up": lambda size, harness, arg: render_tidy_up_body(size, harness, arg),
    "update": lambda size, harness, arg: render_update_body(size, harness, arg),
}

def _load_specs(profile: str, order: list, harness: str, arg_focus: str,
                arg_ticket: str, **extra) -> list:
    """Build the (name, description, body) list for a profile.

    Each name resolves either to a template under templates/skills/<profile>/
    or to a composed body in COMPOSED_BODIES. The description is the template's
    `description:` frontmatter line, kept next to the body it describes so the
    two cannot drift.
    """
    specs = []
    for name in order:
        if name in COMPOSED_BODIES:
            desc = _SKILL_DESCRIPTIONS[(profile, name)]
            body = COMPOSED_BODIES[name](profile, harness, arg_ticket)
        else:
            rel = f"skills/{profile}/{name}.md"
            raw = render.load(rel)
            desc, body = _split_frontmatter(raw)
            body = render.render(body, phases_dir=PHASES_DIR, tools_dir=TOOLS_DIR,
                                 arg_focus=arg_focus, arg_ticket=arg_ticket,
                                 **extra)
        specs.append((name, desc, body))
    return specs

def _split_frontmatter(raw: str):
    """Return (description, body) from a skill template's `---` header."""
    if not raw.startswith("---\n"):
        raise ValueError("skill template missing frontmatter")
    end = raw.index("\n---\n", 3)
    header = raw[4:end]
    body = raw[end + 5:]
    for line in header.splitlines():
        if line.startswith("description:"):
            return line[len("description:"):].strip(), body
    raise ValueError("skill template frontmatter has no description")

def render_skills(specs) -> dict:
    """Agent Skills (SKILL.md, open standard): .claude/skills/<name>/SKILL.md.
    Read by Claude Code and other SKILL.md-compatible harnesses. Every skill is
    a user-sequenced pipeline step with side effects (KB writes, code changes,
    `.ai` commits), so `disable-model-invocation: true` keeps the model from
    auto-triggering them mid-conversation; only an explicit /name invokes them.
    `specs` is a command_specs list (full or small profile)."""
    out = {}
    for name, desc, body in specs:
        hint = ARG_HINTS.get(name)
        hint_line = f"argument-hint: \"{hint}\"\n" if hint else ""
        out[f"{name}/SKILL.md"] = (
            "---\n"
            f"name: {name}\n"
            f'description: "{desc}"\n'
            f"{hint_line}"
            "disable-model-invocation: true\n"
            "---\n"
            f"{body}"
        )
    return out

def render_prompt_files(specs) -> dict:
    """Copilot prompt files: .github/prompts/<name>.prompt.md, VS Code only.
    `specs` is a command_specs list (full or small profile)."""
    out = {}
    for name, desc, body in specs:
        out[f"{name}.prompt.md"] = (
            "---\n"
            f'description: "{desc}"\n'
            "mode: agent\n"
            "---\n"
            f"{body}"
        )
    return out

def render_reviewer_agent(small: bool = False) -> str:
    if small:
        desc = ("Adversarial fresh-context review of a change's diff against "
                "its acceptance criteria. Use for the review gate in /build.")
        input_block = (
            "Input: a code diff plus the change's acceptance criteria in\n"
            "`.ai/changes/<id>/spec.md`."
        )
        coverage = ("- Every acceptance criterion is implemented and, where "
                    "testable, tested.\n"
                    "- The spec is self-contained: paths explicit, interfaces "
                    "stated.")
    else:
        desc = ("Adversarial fresh-context review of a plan or diff against "
                "acceptance criteria. Use for the plan-review gate (Phase 2) "
                "and the ticket review gate (Phase 3).")
        input_block = (
            "Input: a plan (`.ai/knowledgebase/tasks/<id>/plan.md` plus its "
            "task files)\nor a code diff, plus the ticket's acceptance "
            "criteria\n(`.ai/knowledgebase/tasks/<id>/ticket.md`)."
        )
        coverage = ("- Every acceptance criterion is covered by a task (plan) "
                    "or implemented and\n  tested (diff).\n"
                    "- Task files are self-contained: paths explicit, "
                    "interfaces stated.")
    return render.fill("agents/reviewer.md",
                       coverage=coverage,
                       desc=desc,
                       input_block=input_block)

def render_hook_protect_generated() -> str:
    return render.fill("hooks/protect_generated.py", tools_dir=TOOLS_DIR,
                       rules_marker=RULES_MARKER)

def render_hook_ai_repo_clean() -> str:
    return render.load("hooks/ai_repo_clean.py")

def render_hook_regen_index() -> str:
    return render.load("hooks/regen_index.py")

def render_tool_gen_index() -> str:
    return render.fill("tools/gen_index.py", tools_dir=TOOLS_DIR,
                       manifest_parser=_MANIFEST_PARSER)

def render_tool_check_stale() -> str:
    return render.fill("tools/check_stale.py", tools_dir=TOOLS_DIR,
                       manifest_parser=_MANIFEST_PARSER)

def render_tool_gen_rules() -> str:
    return render.fill("tools/gen_rules.py", tools_dir=TOOLS_DIR,
                       rules_marker=RULES_MARKER,
                       manifest_parser=_MANIFEST_PARSER)

def render_tool_probe() -> str:
    """Deterministic repo inventory written into the scaffold. Static: the
    template is a real .py file under templates/tools/."""
    return render.load("tools/probe.py")

def render_settings_json(small: bool = False) -> str:
    """Project settings (.claude/settings.json): a read-only permission allow
    list so exploration runs without a prompt per command, plus hooks that
    enforce protocol rules deterministically. Compound commands (a && b) prompt
    unless every part of the chain matches a rule, so common chain members (cd,
    echo, pwd, read-only git) are included as well. The small profile omits the
    KB tools and the INDEX-protection hook; neither exists there."""
    allow = render.sectioned_list(
        "config/permissions.txt",
        sections=("shared",) if small else ("shared", "large"),
        tools_dir=TOOLS_DIR)
    hooks = {}
    if not small:
        hooks["PreToolUse"] = [
            {
                "matcher": "Write|Edit|MultiEdit",
                "hooks": [
                    {
                        "type": "command",
                        "command": 'python3 "$CLAUDE_PROJECT_DIR/'
                                   '.claude/hooks/protect_generated.py"',
                    }
                ],
            }
        ]
        hooks["PostToolUse"] = [
            {
                "matcher": "Write|Edit|MultiEdit",
                "hooks": [
                    {
                        "type": "command",
                        "command": 'python3 "$CLAUDE_PROJECT_DIR/'
                                   '.claude/hooks/regen_index.py"',
                    }
                ],
            }
        ]
        hooks["SessionStart"] = [
            {
                "hooks": [
                    {
                        "type": "command",
                        "command": 'python3 "$CLAUDE_PROJECT_DIR/'
                                   f'{TOOLS_DIR}/check_stale.py" || true',
                    }
                ],
            }
        ]
    hooks["Stop"] = [
        {
            "hooks": [
                {
                    "type": "command",
                    "command": 'python3 "$CLAUDE_PROJECT_DIR/'
                               '.claude/hooks/ai_repo_clean.py"',
                }
            ],
        }
    ]
    settings = {"permissions": {"allow": allow}, "hooks": hooks}
    return json.dumps(settings, indent=2) + "\n"
